### ISSUE TITLE
Unable to write ISO on Win11

### ISSUE THREAD

**Issue by nathanieloffer** [FedoraQt/MediaWriter#772] opened 2024-11-28 15:16 UTC
I downloaded and installed Fedora Writer, started it and pointed it to the already downloaded Fedora Workstation 41 iso. It had already selected my USB thumb drive so I started the process. Then it stopped with the following errors  
  
```
By writing, you will lose all of the data on General UDisk (15.6 GB).
Selected: Fedora-Workstation-Live-x86_64-41-1.4.iso

Failed to remove partitions from the drive
Failed to write entire image. Total written: 0 byte(s) out of 2.29 GB
Failed to remove partitions from the drive
Failed to write entire image. Total written: 0 byte(s) out of 2.29 GB
Failed to remove partitions from the drive
Failed to write entire image. Total written: 0 byte(s) out of 2.29 GB
```

[FedoraMediaWriter.log](https://github.com/user-attachments/files/17949819/FedoraMediaWriter.log)
[FedoraMediaWriter-helper.log](https://github.com/user-attachments/files/17949820/FedoraMediaWriter-helper.log)

**Comment by grulja** [comment] 2024-11-28 15:28
Does this happen all the time? 

It looks like the main app doesn't have any issue using the WMI interface, but the helper process fails to use it and because of that automatically fails to run some actions. I will look into that.

**Comment by grulja** [comment] 2024-11-28 15:53
Let's see if https://github.com/FedoraQt/MediaWriter/pull/773 makes any change. There will be a Windows installer available to download here https://github.com/FedoraQt/MediaWriter/actions/runs/12072072243 in artifacts after the CI run is finished. Can you please test it?

**Comment by NiranjNinja16** [comment] 2024-11-28 17:40
@grulja , Tried the artifacts Windows installer in your shared link, but it didn't recognize the USB device at all. 
![image](https://github.com/user-attachments/assets/31a8fab2-85b7-4417-8067-747e3d279466)

**Comment by nathanieloffer** [comment] 2024-11-28 20:58
> Let's see if #773 makes any change. There will be a Windows installer available to download here https://github.com/FedoraQt/MediaWriter/actions/runs/12072072243 in artifacts after the CI run is finished. Can you please test it?

This version of the application wasn't able to detect my USB drive

![Screenshot 2024-11-29 045629](https://github.com/user-attachments/assets/5a391a35-4617-491b-8da4-7e734b683258)

**Comment by PalladinRex** [comment] 2024-11-28 22:21
I've been having this same issue with two different USB sticks. One of which is a 32GB stick that should not be having any issues like this, the other is a 128GB stick that I've used in the past for a windows launcher and I know it works. 
I can download the ISO file easily enough, but I'm consistently getting the same error message:

This would be my first time trying to install or use a Linux system as a refugee from Windows, and I can't say that this has been a welcoming issue to run in to. 

![image](https://github.com/user-attachments/assets/8e23e38d-bc87-4ad0-882b-86c3305978ae)
![Screenshot 2024-11-28 171946](https://github.com/user-attachments/assets/535a82cc-1e3b-4746-9293-030480df1400)

**Comment by fbitancurt** [comment] 2024-11-29 02:51
I actually been having the same problem since yesterday and just now came across the issue here on the repo.

Also, this happend to me as well when trying out the new version:

> > Let's see if #773 makes any change. There will be a Windows installer available to download here https://github.com/FedoraQt/MediaWriter/actions/runs/12072072243 in artifacts after the CI run is finished. Can you please test it?
> 
> This version of the application wasn't able to detect my USB drive
> 
> ![Screenshot 2024-11-29 045629](https://private-user-images.githubusercontent.com/212925/390904549-5a391a35-4617-491b-8da4-7e734b683258.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NDc2OTYsIm5iZiI6MTczMjg0NzM5NiwicGF0aCI6Ii8yMTI5MjUvMzkwOTA0NTQ5LTVhMzkxYTM1LTQ2MTctNDkxYi04ZGE0LTdlNzM0YjY4MzI1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOVQwMjI5NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NDZjMjZjZDQyMjQ4NzM3YjljZDExNjUxNTVlY2ZlNjk5YmU0OWZiMmE4NjNlZjhkOTYwMDUzZWFlNWExYzk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1EACgqOzxqT0P7sMrc7J3iZTi4AYfgQoAuSXK76ufi0)

**Comment by grulja** [comment] 2024-11-29 08:29
It looks this broke either with migration to Windows 2022 in the CI or to Qt 6.8. I can also reproduce now on a machine where it worked before. I assume when you download FedoraMediawriter 5.2.0 (not 5.2.1) then it works?

**Comment by nathanieloffer** [comment] 2024-11-29 08:54
Correct, I downgraded to version 5.2.0 and the image wrote to the drive without issue.

**Comment by grulja** [comment] 2024-11-29 09:10
The new fixed build from https://github.com/FedoraQt/MediaWriter/actions/runs/12081786560 now also works for me. Can you please also verify?

**Comment by grulja** [comment] 2024-11-29 12:05
I tested it in a VM and on an laptop with Windows 11 and it worked so I merged it now. I will make a new release with this fix.

**Closed** 2024-11-29 12:04 UTC

**Comment by PalladinRex** [comment] 2024-11-29 12:06
> I tested it in a VM and on an laptop with Windows 11 and it worked so I merged it now. I will make a new release with this fix.

This would be very appreciated! I'm still new to both Linux and Github, and would appreciate a nice and easy "DOWNLOAD" button. :P :P :P 
Thank you again @grulja for the hard work!

**Comment by grulja** [comment] 2024-11-29 12:16
> > I tested it in a VM and on an laptop with Windows 11 and it worked so I merged it now. I will make a new release with this fix.
> 
> This would be very appreciated! I'm still new to both Linux and Github, and would appreciate a nice and easy "DOWNLOAD" button. :P :P :P Thank you again @grulja for the hard work!

Here you go https://github.com/FedoraQt/MediaWriter/releases/tag/5.2.2.

**Comment by PalladinRex** [comment] 2024-11-29 12:34
Still got the same issue. At least now Fedora Writer will also actually reformat my USB drive. 
Does this have anything to do with the fact that I'm on Windows 10 and not 11? Fedora Writer is letting me download the ISO file fine (both 40 AND 41), but won't write them to the USB stick. 

![image](https://github.com/user-attachments/assets/77d444b0-044d-4d96-b81f-2f25f3526b48)

**Comment by grulja** [comment] 2024-11-29 12:40
> Still got the same issue. At least now Fedora Writer will also actually reformat my USB drive. Does this have anything to do with the fact that I'm on Windows 10 and not 11? Fedora Writer is letting me download the ISO file fine (both 40 AND 41), but won't write them to the USB stick.
> 

This is going to be a different issue. Can you try unplugging and plugging your USB drive again? Or maybe trying a different one?
