### ISSUE TITLE
mediawriter half working in fedora workstation 32

### ISSUE THREAD

**Issue by legacychimera247** [FedoraQt/MediaWriter#240] opened 2020-05-15 12:14 UTC
so, i tried to create an usb pen with the app but it does not work, it seems to me that the request for the password to perform the action is sent when the timer is already timed out, and as such the happ is not working, giving me this output in regard on the terminal

`Writing failed: "Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken."`

on the contrary running the app via terminal with sudo work as expected, but surely is not the desired behaviour

**Comment by abitrolly** [comment] 2020-05-22 10:32
I run in from GNOME search string and it could successfully write the USB.

**Comment by MartinBriza** [comment] 2020-05-29 14:04
That's probably not a FMW error, issues like that usually arise from polkit or SELinux misconfiguration (and that may be a distribution-wide problem). Can you try it again after updating your system? If it doesn't work, can you verify if it's still broken if you set SELinux to not enforce? (`sudo setenforce 0`). Another option is also to test doing some modifying change from GNOME Disks, like format your flash drive. If it fails, report a bug against UDisks2 in Fedora.

**Comment by grulja** [comment] 2021-05-12 11:02
Closing this as not a bug in FMW. Please re-open if the issue is still reproducible.

**Closed by grulja** 2021-05-12 11:02 UTC
