### ISSUE TITLE
Can't "restore" flash drives - Windows doesn't see it

### ISSUE THREAD

**Issue by kparal** [FedoraQt/MediaWriter#235] opened 2020-04-15 11:13 UTC
In Windows 10, I burned Fedora Workstation Live on to a 64GB flash drive. That worked fine. When I wanted to reformat it back and used "restore" in FMW, the flash drive is not recognized in Windows. It's not visible in file explorer (no drive, no letter), and it can't be fixed even using Disk Management (all actions report errors). Looking at the flash drive on Linux, it has a MBR table with a single 64GB partition using FAT16 filesystem. FAT16 has a maximum limit of 2GB, so I don't even understand how that's possible, and perhaps this is the reason why Windows don't see the drive. The drive needs to be FAT32, NTFS or exFAT.

Windows 10
FMW 4.1.4

**Comment by An-dz** [comment] 2021-01-11 02:29
If you don't have a Linux machine available here's how you can "fix" your SD.

1) First download the official [SD Formatter](https://www.sdcard.org/downloads/formatter/) from the SD Association
1) Run the SD Formatter tool and click format on the device (it will show a random ID for the device)
1) Open CMD with Admin privileges and call  `diskpart`
1) Execute `list disk` and check which disk number is your USB
1) Execute `select disk #`, where you replace `#` with the number of the disk you checked in the previous command
1) Execute `clean`
1) Execute `create partition primary`
1) Execute `format fs=fat32 label="ANY_NAME_YOU_LIKE" quick`
1) Execute `assign` and now a drive letter is given to your device and you can use it again

If you don't format with SD Formatter, diskpart will complain about not being able to access the device. Trying to set the readonly attribute through diskpart won't have any effect since the problem is the filesystem used as OP has already stated.

**Comment by grulja** [comment] 2021-05-12 11:18
I cannot reproduce. I tried FMW 4.2.1, made a bootable drive with F34 and I was able to restore it afterwards. Closing it now. Please re-open if this issue is still reproducible.

**Closed by grulja** 2021-05-12 11:18 UTC

**Comment by An-dz** [comment] 2021-05-24 01:11
I confirm it's working with 4.2.1
