### ISSUE TITLE
destination drive is not writable

### ISSUE THREAD

**Issue by tc8831** [FedoraQt/MediaWriter#116] opened 2017-09-01 05:44 UTC
when write to the USB with MediaWriter,  it show me 
"
destination drive is not writable
Couldn't open the drive for writing,
Couldn't lock the drive
"
I don't know how to solve this , I use MediaWriter in win7 OS.

**Comment by JerretK** [comment] 2017-09-11 20:52
I'm seeing the same error on Windows 10:

![image](https://user-images.githubusercontent.com/12821765/30296245-5a16cb00-96f8-11e7-9ce9-446bbd66b596.png)

**Comment by MartinBriza** [comment] 2017-09-12 15:16
Do you have the drive open in a file manager, by any chance? Is any other application accessing it at the same moment? Try using the "safely remove this drive" option, too, before writing (you don't have to actually unplug the drive afterwards).

**Comment by JerretK** [comment] 2017-09-13 22:15
I double-checked that it wasn't open, tried rebooting several times but as soon as I tried to write the image I would get a notification from Windows stating that the drive needed to be formatted. It's like the tool unmounted/remounted the drive and Windows tried to access it first. I tried turning off the autoplay capabilities as well but that made no difference.

I went to test it again and it worked today. No idea why, the only thing I can think of is that I had applied some system updates and rebooted yet another time but that doesn't really tell you anything. Shoot, I tried a good half a dozen times before with no success, so I'm not sure what to say.

Regardless, I appreciate the response and work on this tool!

**Comment by glyffa** [comment] 2017-10-20 18:20
I am having this exact problem.  I tried the autoplay changes JerretK used.  I tried turning off anything that might have the drive open like anti-virus software and performance monitors, with no effect.  I tried 2 different brands of USB drives to rule out problems like SanDisk's hidden filesystem restore but it had no change.

Any other suggestions on what to check?

Test info:
* used 16Gb thumb drives that check good.
* always started by removing all partitions on the sticks, then running MediaWriter as administrator.  
* drives always ended up with a 'healthy' 5mb EFI system partition and the rest as unallocated space.

**Comment by MartinBriza** [comment] 2017-10-30 15:40
Having a seemingly botched filesystem layout is actually what you want. There's a special format that makes the drive bootable just fine, however it looks broken from the file managers.
I don't understand how you get to the 5MB EFI partition if you get the error messages though. It shouldn't even start writing when that error occurs. Can you please check if the drive 5MB EFI partition drive is then bootable or not?

**Comment by glyffa** [comment] 2017-11-03 14:18
The drive is not bootable,    I also tried blanking the drive a little harder before running the writer.  I zeroed out the leading 2GB to make sure that any prior format was gone.   Oddly the writer still reported the drive had an existing live filesystem.  

I noticed that the writer does some drive access and has the little side-to-side animation working for a bit then it stops, hangs for a while and pops the same error message.   The drive comes out looking the exact same each time.  

Is there anyway to turn on logging to get a better idea where its falling over?

**Comment by MartinBriza** [comment] 2017-11-03 14:27
Yes, running mediawriter.exe -d will put the log in your Documents folder.

**Comment by glyffa** [comment] 2017-11-03 14:48
I am attaching the log.  I am surprised its looking for an 'F:' drive, the flash drive never shows up with a drive letter that I can see.
[FedoraMediaWriter.log](https://github.com/MartinBriza/MediaWriter/files/1441410/FedoraMediaWriter.log)

**Comment by MartinBriza** [comment] 2017-11-03 14:50
Hmm, it seems you're running version 4.0.95. Can you try it with 4.1.0, please? It has a more verbose debug log.

**Comment by glyffa** [comment] 2017-11-03 15:10
Its working now.  Turns out PerfectDisk was broken, even thoughit was told to ignore the drive it was generally causing misbehavior with all disk management.   I uninstalled that and the write worked perfectly.
Turns out that, like cake, the configuration reporting is a lie :)

**Comment by MartinBriza** [comment] 2017-11-03 15:12
Ha, I was going to suggest an antivirus software could be preventing writing to the drive. Disk management software didn't come up to my mind at all. :) Glad it's working for you now.
I'll leave this report open so the other people can come with their logs or remarks.

**Comment by Karma001** [comment] 2018-05-26 03:46
I have the same issue,but what cause it is ParagonExtFSforWindows , and i totally uninstalled it but still not work , so i quit my antivirus software as MartinBriza suggest , and it worked !
So thanks for all the ideas above , other disk utilities may also cause this issue , but how can we fix it without uninstall any disk utilities ?
ParagonExtFSforWindows 造成了这个问题，也许是其他磁盘工具例如楼主说的 PefactDisk，并且需要退出杀软才行！但是怎么才能不卸载任何磁盘工具来解决这个问题？

**Comment by temberature** [comment] 2020-08-03 01:26
other disk tool may be hold the disk

**Comment by grulja** [comment] 2021-05-14 08:26
Duplicate of https://github.com/FedoraQt/MediaWriter/issues/145.

**Closed by grulja** 2021-05-14 08:26 UTC

**Comment by smbell1979** [comment] 2022-12-11 18:22
Just wanted to add that I was having this same issue and it turns out that HWinfo64 was running for the sensors panel and it was causing the error. 

Took me a bit to figure it out, so I wanted to put that out there in case anyone else had the same issue.

**Comment by anton-x-t** [comment] 2023-02-27 09:15
For me the fix was this for Windows
Run PowerShell as administrator
cd "C:\Program Files (x86)\Fedora Media Writer" (or other install path)
.\mediawriter.exe
