### ISSUE TITLE
macOS - App crashes on finish

### ISSUE THREAD

**Issue by GuiltyDoggy** [FedoraQt/MediaWriter#480] opened 2022-05-06 13:24 UTC
Finishing a write using the Download Automatically option (haven't yet tested custom iso) ends with FMW crashing. The USB disk appears to be fully written and usable, however.
![Failed](https://user-images.githubusercontent.com/52749251/167139991-30bd3667-e2f0-43bb-b038-d8b69efcb12d.png)

[Crash Log.txt](https://github.com/FedoraQt/MediaWriter/files/8640293/Crash.Log.txt)

**Comment by grulja** [comment] 2022-05-06 13:27
This looks like something in Qt crashed thanks to notification. I will try to investigate.

**Comment by grulja** [comment] 2022-05-06 15:15
I think the crash was caused by incompatibility in ImageIO library which we bundled, but we shouldn't. It should be fixed in the latest available build you can find in releases. It works for me now with the latest build.

**Closed by grulja** 2022-05-06 15:15 UTC
Labels: bug, MacOS

**Comment by GuiltyDoggy** [comment] 2022-05-06 15:26
Confirmed fixed here as well on latest build.
