### ISSUE TITLE
Cannot format remaing space on USB or addtional portable Data storage

### ISSUE THREAD

**Issue by madiot** [FedoraQt/MediaWriter#41] opened 2016-11-26 11:15 UTC
First, 
kudo for the flowless feature implementation at least on my brand new HD/SSD laptop.
Really it as a breeze to install Fedora workstation and resize the windows partition.

Now, here is a RFE for you.
The stick i used is 16GB and a lot of space is left unusable on it.

![image](https://cloud.githubusercontent.com/assets/45973/20639937/c98da28e-b3d1-11e6-92d6-05063a4e0428.png)

I wished i could use the linux disk utility to format a partition on that space but it comes back with error : 
![image](https://cloud.githubusercontent.com/assets/45973/20639945/f4e724d2-b3d1-11e6-8c40-55e1ad4c46de.png)

I'd appreciate your thought on what to do to enable access to this wasted space.

**Comment by MartinBriza** [comment] 2016-11-28 09:45
Hello,
thanks for the suggestion. Tentatively I plan to support creating a persistent overlay after the image which would allow you to use the space for your personal data which would be then accessible from the live system. The timeframe right now doesn't allow me to work on that feature though. Some time in the future, maybe. Or as it always goes with open source: patches welcome. :)

**Comment by Jenselme** [comment] 2016-12-03 12:20
Same here, I used MediaWriter on a 32Go USB stick and I now have about 30Go of free space I can't do anything with. Do you think allowing the user to format the free space manually would be easier to do (ie without the need to use it in the Live system)?

Otherwise, the tool is really easy to use. Good job!

**Comment by MartinBriza** [comment] 2016-12-03 12:25
It's not actually related to how the mediawriter works but how the Fedora images are composed - the partition layout utilizes some magic to pretend it's a CD and a regular drive at the same time so you can use the .iso file to bootup from whatever type of drive you have. Making use of the free space on your drive would probably require modifying the partition table which would in turn break at least the checksum but probably also boot completely. The situation in this case is a bit complicated for an easy solution :/

**Comment by grulja** [comment] 2021-05-13 07:50
Duplicate of https://github.com/FedoraQt/MediaWriter/issues/219.

**Closed by grulja** 2021-05-13 07:50 UTC
Labels: enhancement
