### ISSUE TITLE
"Fedora Spins" heading includes alt text?

### ISSUE THREAD

**Issue by daPhipz** [FedoraQt/MediaWriter#323] opened 2021-06-03 12:43 UTC
When opening the Flatpak version 4.2.2 of Fedora MediaWriter on Ubuntu 21.04, I can see buttons to download Workstation 34 and Server 34. There is also a button with 3 dots to expand the list.
When clicking on this button, I see the following:

![fedora](https://user-images.githubusercontent.com/30795174/120646094-751f3b00-c479-11eb-8413-67bb5b156f66.png)

I don't know if it is only an issue with the German translation or with the program as a whole, but the "Fedora Spins" heading looks odd. It seems like the tooltip text slipped in or something...
The whole heading reads (translated back to English): "Fedora Spins Fedora Spins Fedora Spins are alternative Fedora versions, tailored to differe" then it stops.

**Comment by termdew** [comment] 2021-12-31 13:21
![FedoraSpins_Bug](https://user-images.githubusercontent.com/23658248/147825506-602f9d0e-9d37-49d9-9e87-ec96f9f2b85c.png)


This is caused by a faulty translation in translations/de.qm. The MediaWriter project uses .po files now, the issue is gone in the main branch.

Should I provide a fixed .qm file or can we close this issue?

**Comment by daPhipz** [comment] 2021-12-31 14:28
I'll close the issue. Thanks for fixing it!

**Closed** 2021-12-31 14:28 UTC
Labels: bug, GUI
