### ISSUE TITLE
Language selection missing (more like a request I guess)

### ISSUE THREAD

**Issue by AliensInc** [FedoraQt/MediaWriter#127] opened 2017-09-29 18:55 UTC
I'm Swedish but I always, always and again **always** use all OS's (also every program installed) in English just because it makes it so much easier to find help when error messages popup. Try looking for an error message in a language that only 9(?) million people are using, you're getting a result of ZERO, and also because the translation into "my" language is crappy done.
All this "auto-language-set-thingy" that may be selected due to what keyboard language is selected or whatever is just BS.
Pleeeease ask me what language to use. People may sure feel like this is a waste of time to answer that question, but in my case (and I know A LOT of people that feel the same) this is annoying cos we have to change language on the system just to get the correct language in the application we're installing, sometimes not just the K/B language has to be changed. :( :(

thx for listening 👍

**Comment by MartinBriza** [comment] 2017-10-02 13:43
I feel your pain but can you please specify where and how does this happen? Like, do you have something related to Swedish set up somewhere in your system?
We've had this problem on Macs because Qt chose the secondary language instead for some reason, even if the language had been used for the keyboard layout only.
btw I thought there's more Swedes

**Comment by AliensInc** [comment] 2017-10-13 15:40
Sorry for the delay :(

Thx for replying
The only thing I got telling the system it's Swedish is the keyboard. It's a Logitech G510 if that matters.
All other thing is set to US. Even date and time is set to US thus I've made changes to it so it looks
like ISO 8601 which we use. Also have only US language installed.

**Comment by MartinBriza** [comment] 2017-10-30 15:32
So is this Windows, Mac, Linux? Which version/distro?

**Comment by AliensInc** [comment] 2017-10-30 17:35
DOH, Forgot to mention that again, lol
Windows 10 Pro as of now. I will be trying out the Linux version when that machine is up and running.

**Comment by MartinBriza** [comment] 2017-10-30 17:37
Right. So is this FMW 4.1.0? I'll check out on my system to be sure. I'm using English language and Czech keyboard so it should be similar to your setup.

**Comment by AliensInc** [comment] 2017-10-30 17:49
If there ain't no newer version then 4.1.0 after Sept 29th then yes. (Can't find the setup anymore :P)
Do this when you got the time, no hurry :)

**Comment by MartinBriza** [comment] 2017-11-16 11:25
I checked it on a Windows 10 system that was originally German, is now English and I use a Czech keyboard. The FMW UI was in English... :/ 
Can you please send me a screenshot of your Language/Locale (or how exactly is it called) section in your Settings app?

**Comment by RheaAyase** [comment] 2018-05-23 21:37
Same problem. I have czech windows and I hate it, sadly it can not be changed to english (i have it because i had the license)

The app is forcing czech on me, whatever it's reading... please don't read it... manual selection > trying to be smart (KISS)

**Comment by ArturGajowy** [comment] 2018-10-06 10:10
+1

**Comment by grulja** [comment] 2021-05-14 08:02
Duplicate of https://github.com/FedoraQt/MediaWriter/issues/271.

**Closed by grulja** 2021-05-14 08:02 UTC
