### ISSUE TITLE
Resize drive back to normal capacity

### ISSUE THREAD

**Issue by ruslanskorb** [FedoraQt/MediaWriter#288] opened 2021-04-06 23:19 UTC
Hi 👋

Thank you for your work on the MediaWriter!

The download dialog says:

>Your drive will be resized to a smaller capacity. You may resize it back to normal by using Fedora Media Writer; this will remove installation media from your drive.

But I could not find any button in the application that resizes drive back to normal capacity.

I got this question since I ran into a problem:

1. I used an external 1TB ssd disk with xfs file system to create a bootable disk using MediaWriter.
2. Then I used it to install fedora 33 on my computer.
3. After that I tried to format the external ssd disk back to the xfs file system, but got the error `libxfs_device_zero seek to offset 500085686272 failed: Invalid argument`.

It seems to me that it might be related.

Any comments you may have would be grateful.

**Comment by grulja** [comment] 2021-04-07 05:50
With FMW you will be promted on the main screen to restore your drive if it gets detected. I also think you have to format your disk with a new partition table, but I'm not that experienced with this. @MartinBriza do you have any idea?

**Comment by dreua** [comment] 2021-04-07 06:01
Could be a bug because if the 1TB drive? Has the restore function been tested with drives that big?

**Comment by ruslanskorb** [comment] 2021-04-07 20:43
@grulja Thanks for the answer! The message asking to restore the drive did appear in the Windows application. I’ll also check it on Mac OS, and let you know if it is not there.
Regarding the problem with `libxfs_device_zero`, restoring the disk size did not fix it. I was only able to format the disk back to the **xfs** filesystem after preformatting the disk to the **ext2** filesystem using `mke2fs` with the `-c` option.
Could the xfs issue be caused by FMW?

**Comment by ruslanskorb** [comment] 2021-04-08 14:37
The initial question was answered, so I’m closing the issue.

**Comment by ruslanskorb** [comment] 2021-04-24 14:58
@grulja I would like to inform you that I checked the Mac OS version (macOS Big Sur, version 11.2.3, MacBook Pro (15-inch, 2017)). The message asking to restore the drive does not appear here.

**Comment by grulja** [comment] 2021-04-27 06:10
> @grulja I would like to inform you that I checked the Mac OS version (macOS Big Sur, version 11.2.3, MacBook Pro (15-inch, 2017)). The message asking to restore the drive does not appear here.

I can reproduce.

**Comment by grulja** [comment] 2021-05-12 10:51
Fixed with https://github.com/FedoraQt/MediaWriter/pull/309.

**Closed by grulja** 2021-05-12 10:51 UTC
Labels: MacOS, bug
