### ISSUE TITLE
creating a USB key with current Fed 28 LXDE spin fails to complete.

### ISSUE THREAD

**Issue by J-Dunn** [FedoraQt/MediaWriter#179] opened 2018-09-10 12:20 UTC
Having downloaded Fed 28 LXDE spin and selected the iso as a "custon" image, it writes the key , goes through verification, but while the progress bar appears to get to then end , it never displays "finished" and the resulting device is not bootable.

**Comment by MartinBriza** [comment] 2018-09-10 13:36
On what operating system is this happening? What FMW version are you using?

**Comment by J-Dunn** [comment] 2018-09-10 14:43
Bug seen on Fed 28 LXDE installation.

**Comment by grulja** [comment] 2021-05-14 07:59
I'm going to close this bug now as it's more than 2 years old and since than a lot of changes happened. Feel free to re-open this issue if you can still reproduce it.

**Closed by grulja** 2021-05-14 07:59 UTC

**Comment by J-Dunn** [comment] 2021-05-14 08:43
Yep, that's how the majority of Fedora bugs get resolved. Leave them unaddressed for a couple of years, the claim they are no longer current without testing to see whether they still apply. 

Since this garbage "media writer" has already trashed two USB keys for me and caused me public embarrassment when recommending Fedora to a friend, I certainly won't  be doing any further testing. 

I is way more complicated far less efficient than simply dd-ing the iso , plus it is totally unreliable. 

IMO this should not be a recommended installation method. Trashing h/w is not great introduction to Linux.

**Comment by grulja** [comment] 2021-05-14 08:55
1) How do you know it's unaddresses when you haven't tried the latest version?
2) FMW doesn't really trash your USB devices, you can restore them afterwards. Also, using dd-ing is the default option, even the recommended tool livecd-iso-to-disk uses dd command internally.

**Comment by J-Dunn** [comment] 2021-05-14 10:06
"I'm going to close this bug now as it's more than 2 years old and since than a lot of changes happened. Feel free to re-open this issue if you can still reproduce it."

That's how.  And no, the USB devices got thoroughly trashed. I know enough to reclaim most space from flashing a smaller iso image. The devices were DEAD.

**Comment by MartinBriza** [comment] 2021-05-14 10:10
Drives die when they're used. Flash drives in particular don't have the greatest failure rate when a large amount of data gets written to them. You just had back luck, I'm sorry for that but it just happens. There's nothing special about FMW that would trash flash drives.

I have no idea what are you trying to achieve with your comments except to ruin Jan's day.

**Comment by grulja** [comment] 2021-05-14 10:32
> "I'm going to close this bug now as it's more than 2 years old and since than a lot of changes happened. Feel free to re-open this issue if you can still reproduce it."
> 
> That's how. That means you did nothing to fix it. If by happy accident the bug got removed in some other way does not mean it got addressed.
> 

I wasn't in charge of FMW development before so I don't have overview of that has been done and what not. Since your bug report was opened we at least updated to newer versions of Qt everywhere and even this can have major impact on many issues we had. Anyway, since I cannot reproduce your issue and you are not willing to test the latest version then there is nothing we can do.

**Comment by J-Dunn** [comment] 2021-05-14 11:47
Thanks, I'm glad you were not responsible for this mess.  Hopefully those who developed the defective version are now working somewhere where they can be held accountable. 

# Anyway, since I cannot reproduce your issue and you are not willing to test the latest version then there is nothing we can do.

Seems pretty clear you never tried and had no intention of doing so. 
#I'm going to close this bug now as it's more than 2 years old and since than a lot of changes happened. Feel free to re-open this issue if you can still reproduce it.

 I don't intend to do so since I've lost enough hardware already. I even risked it a second time because I could not believe it was the software which was that crap.  Now it's a case of twice bitten, thrice shy. 


# I have no idea what are you trying to achieve with your comments except to ruin Jan's day.

I'm trying to make it clear that trashing user's h/w and then ignoring the issue is not an acceptable outcome. I believe I opened  second bug at that time where I went into more detail about the flash devices getting burnt out. 

I guess that it has not been happening too much since otherwise there would be more reports. 

IIRC this was documented as the primary installation method at the time and dd was an "also ran" at the bottom of serveral different methods. If dd is now the default option this is probably much of the reason. I complained to Fedora about FMW being pushed when it was slow and reliable. 

That's probably the best outcome.  That's all I have to say. Have a nice day.
