### ISSUE TITLE
Media Writer takes long time to browse file system while opening custom image.

### ISSUE THREAD

**Issue by ilikelinux69** [FedoraQt/MediaWriter#320] opened 2021-05-30 21:21 UTC
https://ask.fedoraproject.org/t/fedora-media-writer-very-slow-while-browsing-files-opening-a-custom-image/14577

The problem appears just as normal user. When started in terminal as Sudo it works as expected.

**Comment by grulja** [comment] 2021-05-31 04:58
I believe this is duplicate of https://github.com/FedoraQt/MediaWriter/issues/277 which cannot be fixed in Fedora Media Writer.

**Closed by grulja** 2021-05-31 04:58 UTC
