### ISSUE TITLE
Blank white Screen

### ISSUE THREAD

**Issue by BananaViking** [FedoraQt/MediaWriter#535] opened 2022-07-02 05:42 UTC
Hi
When ever I launch fedora media writer I am faced with a blank white screen, I have tried the version linked from fedora site, latest pre release from github and latest release all have same issue.
I am on windows 8.1, also tried with usb inserted and no usb inserted 
Any help is appreciated thanks.
![fedoramw](https://user-images.githubusercontent.com/106994788/176988191-ef1e2a49-ea3a-48e8-9980-92719af6d96d.PNG)
.

**Comment by grulja** [comment] 2022-07-11 06:51
Hi, I'm sorry, but I don't have any Window 8.1 machine to test this with. Looking into Qt documentation it says only Windows 10 and Windows 11 are supported so it might not be working because of this.

Is there any error when you try to start FMW from a Windows console?

**Comment by lidistat67** [comment] 2022-07-28 19:41
Happens to me too! No clue why. Windows 10

**Comment by grulja** [comment] 2022-08-01 09:14
> Happens to me too! No clue why. Windows 10

What FMW version? Where did you get it from?

**Comment by thizmo** [comment] 2022-08-05 11:15
Hi,

Same here. Downloaded and installed 4 days ago.
From https://silverblue.fedoraproject.org/download --> https://getfedora.org/fmw/FedoraMediaWriter-win32-latest.exe

Edition: Windows 10 Pro
Version: 21H2

HTH.

**Comment by lidistat67** [comment] 2022-08-05 11:39
> > Happens to me too! No clue why. Windows 10
> 
> What FMW version? Where did you get it from?

I got it through getfedora (https://getfedora.org/el/workstation/download/). It's probably 5.0.2

**Comment by lidistat67** [comment] 2022-08-05 11:39
> Hi,
> 
> Same here. Downloaded and installed 4 days ago. From https://silverblue.fedoraproject.org/download --> https://getfedora.org/fmw/FedoraMediaWriter-win32-latest.exe
> 
> Edition: Windows 10 Pro Version: 21H2
> 
> HTH.

Doesn't work for me.

**Comment by thizmo** [comment] 2022-08-05 12:43
> Can you install latest build from https://github.com/grulja/MediaWriter/releases/tag/latest-windows? It should open FMW in a terminal and give you some debug. Can you save the debug into a file and attach it here?

This is the last output.
Think the problem is at the end. ;-)

D@15614ms: ReleaseManager Adding "python classroom" "34" "x86_64"
W@15617ms: Url "https://download.fedoraproject.org/pub/alt/releases/34/Labs/x86_64/images/Fedora-Python-Classroom-Vagrant-34-1.2.x86_64.vagrant-libvirt.box" changed to "https://download.fedoraproject.org/pub/alt/releases/34/Labs/x86_64/images/Fedora-Python-Classroom-Vagrant-34-1.2.x86_64.vagrant-virtualbox.box"
W@15634ms: SHA256 hash of "https://download.fedoraproject.org/pub/alt/releases/34/Labs/x86_64/images/Fedora-Python-Classroom-Vagrant-34-1.2.x86_64.vagrant-virtualbox.box" changed from "13bfce55349e4975b94a4f5987b357bc41ddd998e3d28df68a3d0f776ab39ce2" to "8eb1e472235b8ba17a9a49e9c3a156c0a8f75044d4fdf69bbc60d2675567c81f"
D@15652ms: ReleaseManager Adding "scientific" "34" "x86_64"
D@15655ms: ReleaseManager Adding "scientific" "34" "x86_64"
D@15661ms: ReleaseManager Adding "astronomy" "34" "x86_64"
D@15664ms: ReleaseManager Adding "comp neuro" "34" "x86_64"
D@15669ms: ReleaseManager Adding "design suite" "34" "x86_64"
D@15677ms: ReleaseManager Adding "games" "34" "x86_64"
D@15681ms: ReleaseManager Adding "jam" "34" "x86_64"
D@15685ms: ReleaseManager Adding "python classroom" "34" "x86_64"
W@15691ms: Url "https://download.fedoraproject.org/pub/alt/releases/34/Labs/x86_64/images/Fedora-Python-Classroom-Vagrant-34-1.2.x86_64.vagrant-virtualbox.box" changed to "https://download.fedoraproject.org/pub/alt/releases/34/Labs/x86_64/iso/Fedora-Python-Classroom-Live-x86_64-34-1.2.iso"
W@15710ms: SHA256 hash of "https://download.fedoraproject.org/pub/alt/releases/34/Labs/x86_64/iso/Fedora-Python-Classroom-Live-x86_64-34-1.2.iso" changed from "8eb1e472235b8ba17a9a49e9c3a156c0a8f75044d4fdf69bbc60d2675567c81f" to "df0cac74c1c58f2219e7e387eb5cd527fe0aa158e46c2eda92b50ad4c5a301b1"
D@15729ms: ReleaseManager Adding "robotics" "34" "x86_64"
D@15733ms: ReleaseManager Adding "scientific" "34" "x86_64"
D@15737ms: ReleaseManager Adding "security" "34" "x86_64"
D@15741ms: ReleaseManager Adding "server" "33" "armhfp"
D@15747ms: ReleaseManager Adding "server" "33" "armhfp"
D@15755ms: ReleaseManager Adding "server" "33" "armhfp"
D@15762ms: ReleaseManager Adding "server appliance" "33" "armhfp"
D@15768ms: ReleaseManager Adding "server" "33" "armhfp"
D@15778ms: ReleaseManager Adding "server" "33" "x86_64"
D@15785ms: ReleaseManager Adding "server" "33" "aarch64"
D@15794ms: ReleaseManager Adding "server" "33" "aarch64"
D@15807ms: ReleaseManager Adding "silverblue" "33" "x86_64"
D@15815ms: ReleaseManager Adding "silverblue" "33" "aarch64"
D@15821ms: ReleaseManager Adding "mate" "33" "x86_64"
D@15827ms: ReleaseManager Adding "cinnamon" "33" "x86_64"
D@15835ms: ReleaseManager Adding "kde" "33" "x86_64"
D@15842ms: ReleaseManager Adding "lxde" "33" "x86_64"
D@15855ms: ReleaseManager Adding "lxqt" "33" "x86_64"
D@15860ms: ReleaseManager Adding "soas" "33" "x86_64"
D@15864ms: ReleaseManager Adding "xfce" "33" "x86_64"
D@15869ms: ReleaseManager Adding "kde" "33" "armhfp"
D@15874ms: ReleaseManager Adding "lxde" "33" "armhfp"
D@15879ms: ReleaseManager Adding "lxqt" "33" "armhfp"
D@15884ms: ReleaseManager Adding "mate" "33" "armhfp"
D@15889ms: ReleaseManager Adding "minimal appliance" "33" "armhfp"
D@15896ms: ReleaseManager Adding "soas" "33" "armhfp"
D@15902ms: ReleaseManager Adding "xfce appliance" "33" "armhfp"
D@15907ms: ReleaseManager Adding "workstation" "33" "x86_64"
D@15916ms: ReleaseManager Adding "workstation" "33" "aarch64"
D@15928ms: ReleaseManager Adding "workstation" "33" "armhfp"
D@15937ms: ReleaseManager Adding "workstation appliance" "33" "armhfp"
D@15943ms: ReleaseManager Adding "workstation" "33" "armhfp"
D@15957ms: ReleaseManager Adding "container base" "33" "aarch64"
D@15963ms: ReleaseManager Adding "container minimal base" "33" "aarch64"
D@15967ms: ReleaseManager Adding "container base" "33" "armhfp"
D@15972ms: ReleaseManager Adding "container minimal base" "33" "armhfp"
D@15978ms: ReleaseManager Adding "container base" "33" "x86_64"
D@15981ms: ReleaseManager Adding "container minimal base" "33" "x86_64"
D@15985ms: ReleaseManager Adding "astronomy" "33" "x86_64"
D@15989ms: ReleaseManager Adding "comp neuro" "33" "x86_64"
D@15995ms: ReleaseManager Adding "design suite" "33" "x86_64"
D@15999ms: ReleaseManager Adding "games" "33" "x86_64"
D@16002ms: ReleaseManager Adding "jam" "33" "x86_64"
D@16005ms: ReleaseManager Adding "python classroom" "33" "x86_64"
D@16011ms: ReleaseManager Adding "robotics" "33" "x86_64"
D@16019ms: ReleaseManager Adding "scientific" "33" "x86_64"
D@16025ms: ReleaseManager Adding "security" "33" "x86_64"
D@16030ms: ReleaseManager Adding "python classroom" "33" "x86_64"
D@16043ms: ReleaseManager Adding "python classroom" "33" "x86_64"
D@16050ms: ReleaseManager Adding "scientific" "33" "x86_64"
D@16055ms: ReleaseManager Adding "scientific" "33" "x86_64"
D@16061ms: ReleaseManager Adding "python classroom" "33" "armhfp"
W@16067ms: Could not get disk extents for "\\\\.\\R:"
W@18578ms: Could not get disk extents for "\\\\.\\R:"
W@21094ms: Could not get disk extents for "\\\\.\\R:"
W@71471ms: Failed to create vertex shader: Error 0x80070057: Falscher Parameter.
W@71484ms: Failed to build graphics pipeline state
W@71504ms: Failed to create vertex shader: Error 0x80070057: Falscher Parameter.
W@71513ms: Failed to build graphics pipeline state
W@71534ms: Failed to create vertex shader: Error 0x80070057: Falscher Parameter.
W@71543ms: Failed to build graphics pipeline state
W@71554ms: Failed to create vertex shader: Error 0x80070057: Falscher Parameter.
W@71565ms: Failed to build graphics pipeline state
W@71583ms: Failed to create vertex shader: Error 0x80070057: Falscher Parameter.
W@71588ms: Failed to build graphics pipeline state
W@71635ms: Failed to create vertex shader: Error 0x80070057: Falscher Parameter.
W@71650ms: Failed to build graphics pipeline state
W@71902ms: Failed to create vertex shader: Error 0x80070057: Falscher Parameter.
W@71910ms: Failed to build graphics pipeline state
W@73606ms: Failed to create vertex shader: Error 0x80070057: Falscher Parameter.
W@73613ms: Failed to build graphics pipeline state
W@73624ms: Failed to create vertex shader: Error 0x80070057: Falscher Parameter.
W@73632ms: Failed to build graphics pipeline state
W@73661ms: Failed to create vertex shader: Error 0x80070057: Falscher Parameter.
W@73669ms: Failed to build graphics pipeline state
W@73683ms: Failed to create vertex shader: Error 0x80070057: Falscher Parameter.
W@73687ms: Failed to build graphics pipeline state
W@73702ms: Failed to create vertex shader: Error 0x80070057: Falscher Parameter.
W@73708ms: Failed to build graphics pipeline state
W@73724ms: Failed to create vertex shader: Error 0x80070057: Falscher Parameter.
W@73729ms: Failed to build graphics pipeline state
W@73743ms: Failed to create vertex shader: Error 0x80070057: Falscher Parameter.
W@73748ms: Failed to build graphics pipeline state
W@74360ms: Failed to create vertex shader: Error 0x80070057: Falscher Parameter.
W@74367ms: Failed to build graphics pipeline state
W@74376ms: Failed to create vertex shader: Error 0x80070057: Falscher Parameter.
W@74383ms: Failed to build graphics pipeline state
W@74400ms: Failed to create vertex shader: Error 0x80070057: Falscher Parameter.
W@74407ms: Failed to build graphics pipeline state
W@74416ms: Failed to create vertex shader: Error 0x80070057: Falscher Parameter.
W@74423ms: Failed to build graphics pipeline state
W@74441ms: Failed to create vertex shader: Error 0x80070057: Falscher Parameter.
W@74447ms: Failed to build graphics pipeline state
W@74462ms: Failed to create vertex shader: Error 0x80070057: Falscher Parameter.
W@74470ms: Failed to build graphics pipeline state
W@74497ms: Failed to create vertex shader: Error 0x80070057: Falscher Parameter.
W@74506ms: Failed to build graphics pipeline state

**Comment by grulja** [comment] 2022-08-05 13:02
This looks like a Qt issue https://bugreports.qt.io/browse/QTBUG-78648. It should be fixed in Qt 6.4 which will be released next month. What I can do to try is to backport these fixes to our Qt packages in Fedora and have FMW rebuilt, which should hopefully fix the issue. I will look into that and let you know. Thank you for providing us the log.

**Comment by lidistat67** [comment] 2022-08-05 13:52
> Can you install latest build from https://github.com/grulja/MediaWriter/releases/tag/latest-windows? It should open FMW in a terminal and give you some debug. Can you save the debug into a file and attach it here?

This is the error I'm getting.
[debug.txt](https://github.com/FedoraQt/MediaWriter/files/9269211/debug.txt)

**Comment by grulja** [comment] 2022-08-08 10:15
Can you try following build https://jgrulich.fedorapeople.org/FedoraMediaWriter-win32-5.0.2.exe? It should have Qt that has fixes for above mentioned issue.

**Comment by grulja** [comment] 2022-08-08 12:10
One more question. Do you run FMW in a virtual machine?

**Comment by lidistat67** [comment] 2022-08-10 19:06
> Can you try following build https://jgrulich.fedorapeople.org/FedoraMediaWriter-win32-5.0.2.exe? It should have Qt that has fixes for above mentioned issue.

Thank you. That solves the issue for me. I'm not using any virtual machine.

**Comment by grulja** [comment] 2022-08-15 05:51
Thank you. We backported these fixes to official Qt packages in Fedora and I asked here https://pagure.io/releng/issue/10851 for a new official build which should be available on getfedora.org once done.

**Comment by grulja** [comment] 2022-08-31 13:07
We should have FMW 5.0.3 on getfedora.org already built with patched Qt so this issue should be hopefully gone.

**Closed by grulja** 2022-08-31 13:07 UTC
