### ISSUE TITLE
Can't open on my mac due to "Cannot check for malicious software"

### ISSUE THREAD

**Issue by ColtonIdle** [FedoraQt/MediaWriter#387] opened 2022-01-15 01:42 UTC
When I double click on it I get this error
<img width="372" alt="Screen Shot 2022-01-14 at 8 31 09 PM" src="https://user-images.githubusercontent.com/31751141/149604046-a3769011-1175-4452-b08a-8acd3297cdff.png">

TYpically when I get this, I just right click and click open from there, but I get this

<img width="372" alt="Screen Shot 2022-01-14 at 8 31 19 PM" src="https://user-images.githubusercontent.com/31751141/149604056-f0c968ac-d0d6-4d97-ad5f-81dd1943c111.png">

if I click open. Nothing happens. I'm on an m1 mac. Maybe thats the issue?

**Comment by grulja** [comment] 2022-01-17 13:43
Duplicate of https://github.com/FedoraQt/MediaWriter/issues/317.

**Closed by grulja** 2022-01-17 13:43 UTC
