### ISSUE TITLE
FMW version string can't be copied

### ISSUE THREAD

**Issue by kparal** [FedoraQt/MediaWriter#477] opened 2022-05-06 13:09 UTC
When reporting a bug, I'd like to copy the program version from the About dialog. But the text is not selectable.

![Screenshot from 2022-05-06 15-09-29](https://user-images.githubusercontent.com/755451/167137740-be9565f7-6936-47be-98f0-39757925f182.png)

**Comment by grulja** [comment] 2022-05-06 13:33
Duplicate of https://github.com/FedoraQt/MediaWriter/issues/242.

This is a QML issue, probably nothing we can do about it as of now.

**Closed by grulja** 2022-05-06 13:33 UTC

**Comment by kparal** [comment] 2022-05-06 13:59
Sure you can do. You can add a "copy" button next to the version string ;-)
