### ISSUE TITLE
Jiggly progress bar download text

### ISSUE THREAD

**Issue by allanday** [FedoraQt/MediaWriter#422] opened 2022-04-21 10:26 UTC
The progress bar text frequently changes width as the download size changes, which doesn't look great. Would it be possible to use tabular numbers for the download size? That would reduce the jiggle.

**Comment by grulja** [comment] 2022-04-21 13:10
This is duplicate of https://github.com/FedoraQt/MediaWriter/issues/278.

**Closed by grulja** 2022-04-21 13:10 UTC
Labels: nextgen

**Comment by allanday** [comment] 2022-04-21 13:25
Sorry for the noise!

**Comment by grulja** [comment] 2022-04-21 13:28
> Sorry for the noise!

No problem at all. It's hard to get oriented in the list of bugs we have reported against FMW.
