### ISSUE TITLE
Can't regain free space

### ISSUE THREAD

**Issue by ameenross** [FedoraQt/MediaWriter#114] opened 2017-08-30 12:17 UTC
MW says that the free space can be regained by re-inserting the media while MW is running. However, I see no option to do so, and it doesn't happen automatically. Also, when using `gnome-disks` to try to create a partition of the free space, I get an error:

> physical block size is 2048 bytes, but Linux says it is 512

**Comment by MartinBriza** [comment] 2017-08-30 12:18
What operating system is this, please?

2017-08-30 14:17 GMT+02:00 Ameen Ross <notifications@github.com>:

**Comment by ameenross** [comment] 2017-08-30 12:19
Fedora 26. I also tried gnome disks afterwards in an Ubuntu system. No luck

**Comment by MartinBriza** [comment] 2017-08-30 12:24
Thanks. I'll check if the drive detection still works.
To fix this problem for now, run this:
dd if=/dev/zero of=/dev/sdX bs=1M count=16
and change /dev/sdX to the block device of your flash drive. Then reinsert
it and you should be able to modify the partition layout in Gnome Disks.

2017-08-30 14:19 GMT+02:00 Ameen Ross <notifications@github.com>:

**Comment by ameenross** [comment] 2017-08-30 12:27
I can clear it out, that's not the problem. I want a bootable disk, but I want some extra space for some files, so I don't have to carry around 2 flash drives

**Comment by MartinBriza** [comment] 2017-08-30 12:46
Ah, that's not what the "regaining" option does. It should just wipe the drive and put a single empty FAT32 partition over it whole. To get a drive where you can put some files, you can create another partition at the end of the drive. That will work just in Linux though.
We've had a Google Summer of Code project this year that added a possibility to create a persistent storage partition at the end of the written image but it's not merged yet and it'll take a while until it is. You can take a look at @squimrel 's fork of this repository if you want to try that. It won't solve the problem with being Linux-only though.

**Comment by ameenross** [comment] 2017-08-30 12:58
> Ah, that's not what the "regaining" option does.

What I meant is that I make use of the remaining 14GB of unpartitioned free space on the drive.

> you can create another partition at the end of the drive

It's not allowing me to create a partition manually (neither gparted nor gnome-disks).

**Comment by MartinBriza** [comment] 2017-08-30 13:39
Yeah, some of the partition manipulation tools see the device with the wrong block size. Some of them do it right though, I just can't tell you which ones from the top of my head, unfortunately. Maybe parted from the commandline?

**Comment by ameenross** [comment] 2017-08-30 14:06
Haven't tried. Gparted showed my drive as 64GB at some point. Is there a way to fix it? I'd rather not keep trying tools until I find one that works

**Comment by MartinBriza** [comment] 2017-08-30 15:44
No, there is no way to fix that. The Fedora images written by FMW to your drive are in a format that claims to have blocks of 2048 bytes while the flash drive actually has 512 byte large blocks. This is caused by the isohybrid format Fedora uses for its images to make booting them possible in as many ways as possible (CD and USB on different platforms).

**Comment by ameenross** [comment] 2017-08-30 16:28
Alright, it worked in fdisk. I just created the partition with `n` and used the defaults. Then I could format the volume.

**Comment by MartinBriza** [comment] 2017-08-31 09:38
Thanks for letting us know what helped.
What "partition in a partition" hack do you have on your mind please?

**Comment by ameenross** [comment] 2017-08-31 09:50
Well, here's the output of fdisk, you'll see what I mean:

```
Device     Boot   Start      End  Sectors  Size Id Type
/dev/sdb1  *          0  3053567  3053568  1,5G  0 Empty
/dev/sdb2        104772   117775    13004  6,4M ef EFI (FAT-12/16/32)
/dev/sdb3        117776   145855    28080 13,7M  0 Empty
```

**Comment by squimrel** [comment] 2017-08-31 12:23
@ameenross The tools you tried all use libparted.
The warning you're seeing `physical block size is 2048 bytes, but Linux says it is 512` can be ignored when operating libparted correctly but then another issue comes up due to the isohyrid layout which I could explain in depth but you're probably not interested.

Having a partition inside of a partition is totally legit and has nothing to do with anything. Basically sdb1 contains image files and sdb2 and sdb3 are pointing to the location of those files which are file systems. So again it's totally legit.

**Comment by ameenross** [comment] 2017-08-31 13:11
> The tools you tried all use libparted.

You mean the tools that failed? Fdisk did work, it didn't even say anything about a block size of 2048.

> isohyrid layout which I could explain in depth but you're probably not interested.

Of course I'm interested. I asked the question purely [out of curiosity](https://github.com/MartinBriza/MediaWriter/issues/114#issuecomment-326045450) and no other reason.

> Having a partition inside of a partition is totally legit and has nothing to do with anything.

I know it's legitimate, that's not why I asked. My point is that the first partition starts at sector 0 (which I assume is to make some systems happy, similar to what UDF tools do). But that first sector contains the MBR with partition table whole. So I was wondering if that might be the reason it can't be changed.

**Comment by squimrel** [comment] 2017-09-01 07:06
Yes the other tools that failed not fdisk.

The image you're using uses the isohybrid layout which deploys up to three partition tables. The reason for that is compatibility when booting on different systems.
The three partition tables are the MBR one (which libfdisk works on if available), a GPT partition table and an apple partition table.

libparted understands all those three partition tables but it chooses to operate on the apple partition table   instead of the other ones if available. The issue with the apple partition table is that only three partitions fit on it. Therefore even if you'd pass the libparted warning you wouldn't be successful with libparted.

Partitioning works with libfdisk because it modifies the MBR partition table as mentioned before. I'd guess that you'd not be able to use the partition you added on MacOS for example because it'll probably prefer the apple partition table which still only has three partitions since libfdisk only modified the MBR partition table.

The only reason why fdisk seems to do the job is because fdisk and linux seem to prefer the MBR partition table if available.

That the first partition starts at zero does not break anything. The first partition in your case is an iso9660 image. According to the specification of iso9660 (ECMA-119) the first 32kB are ignored. This is because iso9660 was designed for CDs. So even though it's ignored it does contain stuff like the partition tables in the image you've got.

I hope that clears things up for you.

**Comment by grulja** [comment] 2021-05-13 08:09
Duplicate of https://github.com/FedoraQt/MediaWriter/issues/219.

**Closed by grulja** 2021-05-13 08:09 UTC
