### ISSUE TITLE
SHA256 checksums

### ISSUE THREAD

**Issue by ghost** [FedoraQt/MediaWriter#221] opened 2019-11-19 01:12 UTC
from 
https://github.com/FedoraQt/MediaWriter/issues/143#issuecomment-555284728

are they like this-> https://github.com/VSCodium/vscodium/releases/download/1.40.1/VSCodium-win32-x64-1.40.1.zip.sha256, cause its going to be another unnecessary process to separate the SHA256 hashes from unneeded stuff.

How about doing it like Ubuntu ISOs. Checksums and GPG signs? that sounds good and flexible enough for most use-cases. And don't forget the public key for GPG signs.

or just do it like https://getfedora.org/en/security/, though `.SHA256` at the end of filename would be better, you get(the hash type) what you see.

---

 asd-collab

**Comment by asd-collab** [comment] 2019-11-19 01:16
aside:

link to this repo from https://getfedora.org/en/workstation/download/, some users don't even realise that they are consenting to use a open-soruce program by downloading 'Fedora Media Writer'.
----

asd-collab

**Comment by grulja** [comment] 2021-05-13 10:24
Duplicate of https://github.com/FedoraQt/MediaWriter/issues/143.

**Closed by grulja** 2021-05-13 10:24 UTC
